config/routes.rb
FbApp::Application.routes.draw do
  get "/auth/facebook/callback" => "sessions#create"
  get "/auth/failure" => "sessions#failure"
  get "/auth/deauthorize" => "sessions#deauthorize"
  get "/redirected" => "application#safari_return"

  get "/signin" => "sessions#new", as: :signin
  get "/signout" => "sessions#destroy", as: :signout
end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of   :name, :uid
  validates_uniqueness_of :uid

  scope :expired_tokens, -> { where("token IS NOT NULL and token_expires_at IS NULL or token_expires_at < ?", Time.now) }

  def invitation_pending?
    invited == true && accepted == false
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
         user.token = auth['credentials']['token']
      end
    end
  end

  def facebook
    return nil unless self.token
    @fb ||= MiniFB::OAuthSession.new(self.token)

    rescue MiniFB::FaceBookError => e
      logger.error "[User#facebook] #{e.message}"
      case e.message
      when /not authorized application/
        return nil
      when /Error validating access token/
        refresh_token!
        return facebook
      end
  end

  def long_lived_token?
    self.token && self.token_expires_at && self.token_expires_at > Time.now
  end

  def refresh_token!
     exchange = MiniFB.fb_exchange_token(ENV['FACEBOOK_APP_ID'], ENV['FACEBOOK_SECRET'], self.token)
     self.update_attribute(:token, exchange["access_token"])
     self.update_attribute(:token_expires_at, exchange["expires"].to_i.seconds.from_now)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from MiniFB::FaceBookError, with: :remove_token

  before_filter :notification_callback? #TODO: filter only root_path
  before_filter :allow_iframe
  after_filter  :allow_iframe

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  def remove_token(exception)
    logger.info "\n[MiniFB::Error] #{exception.message}"
    if exception.message.include?("Session does not match current stored session") || exception.message.include?("Invalid OAuth access token")
      if current_user
        current_user.update_attribute(:token, nil)
        redirect_to "/auth/facebook"
      end
    end
  end

  def safari_return
    cookies["redirected"]=true
    redirect_to "#{ENV['FACEBOOK_CANVAS']}#{params[:redirect_to]}"
  end

  private

    def notification_callback?
      if params["fb_source"] == "notification" &&
        params["app_request_type"] == "user_to_user" && params["signed_request"]
        envelope = Facebook::Request.parse_signed_request(params["signed_request"], 6300)
        mother_uid = envelope["user_id"]
        if mother = Mother.find_by_uid(mother_uid)
          logger.debug "Mother with #{mother_uid} found. Redirect"
          redirect_to "/auth/facebook?state=invitation"
        else
          logger.warn "Invited user #{mother_uid} doesn't exist"
        end
      end
    end

    def current_user
      @current_user||= begin
        if params["signed_request"]
          envelope ||= Facebook::Request.parse_signed_request(params["signed_request"], 6300)
          logger.info "\n Current User #{envelope["user_id"]} \n" if envelope["user_id"]
          User.find_by_uid envelope["user_id"]
        else
          User.find(session[:user_id]) if session[:user_id]
        end
      rescue Exception => e
        nil
      end
      @current_user
    end

    def user_signed_in?
      return true if current_user
    end

    def authenticate_user!
      if !current_user
        #redirect_to root_url, :alert => t("notices.need_sign_in")
        redirect_to "/auth/facebook"
      else
        redirect_to rankings_path, notice: t("notices.is_inactive") if !current_user.active
      end
    end

    def allow_iframe
      response.headers.except! 'X-Frame-Options'
    end

    def only_canvas
      head :not_found and return false unless params["signed_request"]
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def new
    redirect_to "/auth/facebook"
  end

  def create
    auth = request.env["omniauth.auth"]
    logger.info "\n Create session for: #{auth['uid']} #{auth['info']['name']} \n"
    if params["state"] == "invitation"
      user = MotherService.access(auth, true)
      redirect_to root_url(anchor: "login"), :notice => t("notices.not_invited") unless user
    else
      user = UserService.access(auth)
    end

    reset_session
    session[:user_id] = user.id

    if user.has_mother?
      redirect_to rankings_path(anchor: "login"), :notice => t("notices.sign_in")

    elsif !user.has_mother? && user.is_mother?
      redirect_to rankings_path(anchor: "login"), :notice => t("notices.sign_in")

    else
      redirect_to root_path(anchor: "login"), :notice => t("notices.sign_in")
    end
  end

  def destroy
    reset_session
    redirect_to root_url(anchor: 'logout'), :notice => t("notices.sign_out")
  end

  def deauthorize
    envelope = Facebook::Request.parse_signed_request(params["signed_request"], 6300)
    logger.info "[Sessions] Deauthorization #{envelope.inspect}"
    user = User.find_by_uid envelope["user_id"]
    head :not_found and return
    user.destroy
    logger.debug "[Sessions] Destroy user #{user.inspect}"
    head :ok
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_metadata
    out = {}
    session_key      = Rails.application.config.session_options[:key]
    out['session']   = cookies[session_key]
    out['csrfParam'] = Rack::Utils.escape_html(request_forgery_protection_token)
    out['csrfToken'] = Rack::Utils.escape_html(form_authenticity_token)
    #out['appUrl']    = $fb_url
    out
  end

  def safari_redirect
    url = url_for(controller: params[:controller], action: params[:action])
    "#{ENV['HOST']}/redirected?redirect_to=#{url}"
  end

  def facebook_iframed_url
    "#{ENV['FACEBOOK_CANVAS']}#{request.path}"
  end

end

app/views/layouts/_facebook_sdk.html.erb
<div id="fb-root"></div>

<script type="text/javascript">
  $(document).ready(function() {
    window.fbAsyncInit = function() {
      FB.init({
        appId  : '<%= ENV['FACEBOOK_APP_ID'] %>',
        status : true, // check login status
        cookie : true, // enable cookies to allow the server to access the session
        xfbml  : false  // parse XFBML
      });

      <%= content_for?(:fb_javascript) ? yield(:fb_javascript) : "" %>
    };

    // Load the SDK asynchronously
    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/all.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
  });
</script>

app/views/layouts/_messages.html.erb
<% false && flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

<% if flash.present? || content_for?(:messages) %>
  <div class="alert notificacion notification">
    <button class="close" data-dismiss="alert">&#215;</button>
    <div class="clearfix"></div>
    <div class="notificacion-contenido">
      <% flash.each do |name, msg| %>
        <%= msg %>
      <% end %>
      <%= content_for?(:messages) ? yield(:messages) : "" %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-static-top">
  <div class="navbar-inner">
    <%= link_to "Ranking Facebook's User", root_path, :class => 'brand' %>
    <ul class='nav pull-right'>
      <% if user_signed_in? %>
        <li>
         <p class='navbar-text'>Logged in as <%= current_user.name %></p>
        </li>
        <li>
          <%= link_to 'Logout', signout_path %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Login', signin_path %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_share.html.erb
<div class="btn-fb-login btn-fb-share">
  <span class="icon icon-fb"></span>
  <%= link_to "Compartir", "#", class: "title", id: "fb-share"  %>
</div>

<% content_for :fb_javascript do %>
  $('#fb-share').click(function(e){ 
    e.preventDefault();
    FB.ui({
      method: 'feed',
          link: '<%= ENV['FACEBOOK_CANVAS'] %>',
          caption: 'Participa y ganate un viaje a Wall Street',
          description: '<%= share_description %>'
          }, function(response){});
  });
<% end %>

app/views/layouts/_signup.html.erb
<div class="btn-fb-login">
  <span class="icon icon-fb"></span>
  <%= link_to "Accede con Facebook", "/auth/facebook", class: "title"  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en" xmlns="http://www.w3.org/1999/html"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <title></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" /> 
    <meta name="description" content="Tu mamá en Facebook cotiza en bolsa con el Banco Hipotecario.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:image" content="<%= "#{ENV['HOST']}#{asset_path 'tu_mama_cotiza.jpg'}" %>" />
    <link rel="image_src" href="<%= "#{ENV['HOST']}#{asset_path 'tu_mama_cotiza.jpg'}" %>" />
    <meta property="og:url" content="<%= ENV['FACEBOOK_CANVAS'] %>" />
    <meta property="fb:app_id" content="<%= ENV['FACEBOOK_APP_ID'] %>" /> 
    <meta property="og:title" content="Banco Hipotecario - Tu Mamá Cotiza en Bolsa"/>
    <meta property="og:site_name" content="Tu Mamá Cotiza"/>
    <meta property="og:description" content="Tu mamá en Facebook cotiza en bolsa con el Banco Hipotecario." />

   <!--<meta name="viewport" content="initial-scale=1; maximum-scale=1">-->

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <script type="text/javascript">
      // If our app is not loaded in a canvas, refresh and load inside a canvas
      <% if !@not_canvas && Rails.env == "production" && !request.path.include?("/admin/") %>
        if (window == window.top) {
          window.top.location = '<%= facebook_iframed_url %>';
        }

        //If userAgent is safari, redirect to allow cookies from ifram
        if (BrowserDetect.browser.indexOf("Safari") > -1 && document.cookie.indexOf("redirected") == -1) {
          //console.log('no cookie, no glory');
          window.top.location = '<%= safari_redirect  %>'
        }
      <% end %>
    </script>

    <%= yield(:head) %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
      <%#= render 'layouts/navigation' %>
      <div id="container" >
          <%= render 'layouts/messages' %>
          <%= yield %>
      </div> <!--! end of .container -->

    <%= render "layouts/facebook_sdk" %>
    <script type="text/javascript">
      <%= content_for?(:javascript) ? yield(:javascript) : "" %>
    </script>

    <script type="text/javascript">
      // Enable CJAX browsing (ie: PushState on smart browsers, full top redirects for IE.)
      //initCJAX(window);
    </script>
  </body>
</html>